# Generated by Django 5.2.14 on 2026-05-07 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], default='Tenant', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('area', models.CharField(choices=[('Ntinda', 'Ntinda'), ('Kisaasi', 'Kisaasi'), ('Naalya', 'Naalya'), ('Kireka', 'Kireka'), ('Najjera', 'Najjera'), ('Bukoto', 'Bukoto'), ('Kyaliwajjala', 'Kyaliwajjala'), ('Mukono', 'Mukono'), ('Bweyogerere', 'Bweyogerere'), ('Namugongo', 'Namugongo')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('access_road_description', models.TextField()),
                ('facilities', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='property_videos/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='brokerage.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
